chore(ci): comment out getting podman from brew

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -106,9 +106,9 @@ jobs:
       # TODO: remove me when we have a new podman in 26.04 runners
       # needed because old podman doesn't push layer annotations for
       # the rechunker at all
-      - name: Install Podman from Brew
-        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
-        run: /home/linuxbrew/.linuxbrew/bin/brew install podman || exit 1
+      # - name: Install Podman from Brew
+      #   if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
+      #   run: /home/linuxbrew/.linuxbrew/bin/brew install podman || exit 1
 
       - name: Login to GitHub Container Registry
         if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
@@ -129,13 +129,18 @@ jobs:
           MAX_RETRIES: 3
         run: |
           set -x
-          # HACK: push two times so layer annotations are present
-          # TODO: remove me when https://github.com/containers/podman/issues/27796 fixed
-          for _ in $(seq 2); do
-            for tag in $IMAGE_TAGS; do
-              for i in $(seq "${MAX_RETRIES}"); do
-                sudo /home/linuxbrew/.linuxbrew/bin/podman push --digestfile=/tmp/digestfile "${IMAGE_REGISTRY}/${IMAGE_NAME}:${DEFAULT_TAG}" "${IMAGE_REGISTRY}/${IMAGE_NAME}:${tag}" && break || sleep $((5 * i));
-              done
+          # # HACK: push two times so layer annotations are present
+          # # TODO: remove me when https://github.com/containers/podman/issues/27796 fixed
+          # for _ in $(seq 2); do
+          #   for tag in $IMAGE_TAGS; do
+          #     for i in $(seq "${MAX_RETRIES}"); do
+          #       sudo /home/linuxbrew/.linuxbrew/bin/podman push --digestfile=/tmp/digestfile "${IMAGE_REGISTRY}/${IMAGE_NAME}:${DEFAULT_TAG}" "${IMAGE_REGISTRY}/${IMAGE_NAME}:${tag}" && break || sleep $((5 * i));
+          #     done
+          #   done
+          # done
+          for tag in $IMAGE_TAGS; do
+            for i in $(seq "${MAX_RETRIES}"); do
+              sudo podman push --digestfile=/tmp/digestfile "${IMAGE_REGISTRY}/${IMAGE_NAME}:${DEFAULT_TAG}" "${IMAGE_REGISTRY}/${IMAGE_NAME}:${tag}" && break || sleep $((5 * i));
             done
           done
           echo "remote_image_digest=$(< /tmp/digestfile)" | tee "${GITHUB_OUTPUT}"
